window.dailyArabicQuestionBank = (() => {
  const core = [
    { category: "问候", zh: "你好", ar: "مرحبا", rom: "marhaban" },
    { category: "问候", zh: "愿你平安", ar: "السلام عليكم", rom: "as-salamu alaykum" },
    { category: "问候", zh: "也愿你平安", ar: "وعليكم السلام", rom: "wa alaykum as-salam" },
    { category: "问候", zh: "早上好", ar: "صباح الخير", rom: "sabah al-khayr" },
    { category: "问候", zh: "晚上好", ar: "مساء الخير", rom: "masa al-khayr" },
    { category: "问候", zh: "你好吗？", ar: "كيف حالك؟", rom: "kayfa haluka" },
    { category: "问候", zh: "我很好", ar: "أنا بخير", rom: "ana bikhayr" },
    { category: "问候", zh: "谢谢", ar: "شكرا", rom: "shukran" },
    { category: "问候", zh: "不客气", ar: "عفوا", rom: "afwan" },
    { category: "问候", zh: "再见", ar: "مع السلامة", rom: "ma'a as-salamah" },
    { category: "礼貌用语", zh: "请", ar: "من فضلك", rom: "min fadlik" },
    { category: "礼貌用语", zh: "对不起", ar: "آسف", rom: "asif" },
    { category: "礼貌用语", zh: "没关系", ar: "لا مشكلة", rom: "la mushkila" },
    { category: "礼貌用语", zh: "可以吗？", ar: "هل يمكن؟", rom: "hal yumkin" },
    { category: "礼貌用语", zh: "好的", ar: "حسنا", rom: "hasanan" },
    { category: "礼貌用语", zh: "是", ar: "نعم", rom: "na'am" },
    { category: "礼貌用语", zh: "不是", ar: "لا", rom: "la" },
    { category: "礼貌用语", zh: "等一下", ar: "انتظر قليلا", rom: "intazir qalilan" },
    { category: "礼貌用语", zh: "请再说一遍", ar: "كرر من فضلك", rom: "karrir min fadlik" },
    { category: "礼貌用语", zh: "我不明白", ar: "أنا لا أفهم", rom: "ana la afham" },
    { category: "日常句子", zh: "我叫小西", ar: "اسمي شيشي", rom: "ismi xixi" },
    { category: "日常句子", zh: "你叫什么名字？", ar: "ما اسمك؟", rom: "ma ismuka" },
    { category: "日常句子", zh: "我来自中国", ar: "أنا من الصين", rom: "ana min as-sin" },
    { category: "日常句子", zh: "我住在阿布扎比", ar: "أنا أسكن في أبوظبي", rom: "ana askun fi abu dhabi" },
    { category: "日常句子", zh: "今天很热", ar: "اليوم حار جدا", rom: "al-yawm har jiddan" },
    { category: "日常句子", zh: "我很开心", ar: "أنا سعيد", rom: "ana sa'id" },
    { category: "日常句子", zh: "我有点累", ar: "أنا متعب قليلا", rom: "ana mut'ab qalilan" },
    { category: "日常句子", zh: "我想喝水", ar: "أريد أن أشرب ماء", rom: "urid an ashrab ma" },
    { category: "日常句子", zh: "我想吃饭", ar: "أريد أن آكل", rom: "urid an akul" },
    { category: "日常句子", zh: "我们走吧", ar: "هيا بنا", rom: "hayya bina" },
    { category: "学校", zh: "学校", ar: "مدرسة", rom: "madrasa" },
    { category: "学校", zh: "老师", ar: "معلم", rom: "muallim" },
    { category: "学校", zh: "学生", ar: "طالب", rom: "talib" },
    { category: "学校", zh: "书", ar: "كتاب", rom: "kitab" },
    { category: "学校", zh: "笔", ar: "قلم", rom: "qalam" },
    { category: "学校", zh: "作业", ar: "واجب", rom: "wajib" },
    { category: "学校", zh: "数学", ar: "رياضيات", rom: "riyadiyat" },
    { category: "学校", zh: "科学", ar: "علوم", rom: "ulum" },
    { category: "学校", zh: "我在学校", ar: "أنا في المدرسة", rom: "ana fi al-madrasa" },
    { category: "学校", zh: "这是我的书", ar: "هذا كتابي", rom: "hadha kitabi" },
    { category: "家庭", zh: "爸爸", ar: "أبي", rom: "abi" },
    { category: "家庭", zh: "妈妈", ar: "أمي", rom: "ummi" },
    { category: "家庭", zh: "哥哥或弟弟", ar: "أخ", rom: "akh" },
    { category: "家庭", zh: "姐姐或妹妹", ar: "أخت", rom: "ukht" },
    { category: "家庭", zh: "家", ar: "بيت", rom: "bayt" },
    { category: "家庭", zh: "我的家人", ar: "عائلتي", rom: "ailati" },
    { category: "家庭", zh: "这是我的爸爸", ar: "هذا أبي", rom: "hadha abi" },
    { category: "家庭", zh: "这是我的妈妈", ar: "هذه أمي", rom: "hadhihi ummi" },
    { category: "食物", zh: "水", ar: "ماء", rom: "ma" },
    { category: "食物", zh: "牛奶", ar: "حليب", rom: "halib" },
    { category: "食物", zh: "果汁", ar: "عصير", rom: "asir" },
    { category: "食物", zh: "面包", ar: "خبز", rom: "khubz" },
    { category: "食物", zh: "米饭", ar: "أرز", rom: "aruzz" },
    { category: "食物", zh: "鸡肉", ar: "دجاج", rom: "dajaj" },
    { category: "食物", zh: "鱼", ar: "سمك", rom: "samak" },
    { category: "食物", zh: "苹果", ar: "تفاح", rom: "tuffah" },
    { category: "食物", zh: "香蕉", ar: "موز", rom: "mawz" },
    { category: "食物", zh: "这个很好吃", ar: "هذا لذيذ", rom: "hadha ladhidh" },
    { category: "餐厅", zh: "菜单在哪里？", ar: "أين القائمة؟", rom: "ayna al-qaimah" },
    { category: "餐厅", zh: "我想点这个", ar: "أريد هذا", rom: "urid hadha" },
    { category: "餐厅", zh: "请给我水", ar: "من فضلك أعطني ماء", rom: "min fadlik atini ma" },
    { category: "餐厅", zh: "多少钱？", ar: "كم السعر؟", rom: "kam as-sir" },
    { category: "餐厅", zh: "账单请给我", ar: "الحساب من فضلك", rom: "al-hisab min fadlik" },
    { category: "地点", zh: "这里", ar: "هنا", rom: "huna" },
    { category: "地点", zh: "那里", ar: "هناك", rom: "hunak" },
    { category: "地点", zh: "厕所在哪里？", ar: "أين الحمام؟", rom: "ayna al-hammam" },
    { category: "地点", zh: "商店在哪里？", ar: "أين المتجر؟", rom: "ayna al-matjar" },
    { category: "地点", zh: "我去学校", ar: "أذهب إلى المدرسة", rom: "adhhab ila al-madrasa" },
    { category: "交通", zh: "汽车", ar: "سيارة", rom: "sayyara" },
    { category: "交通", zh: "飞机", ar: "طائرة", rom: "taira" },
    { category: "交通", zh: "公共汽车", ar: "حافلة", rom: "hafila" },
    { category: "交通", zh: "我坐车去", ar: "أذهب بالسيارة", rom: "adhhab bis-sayyara" },
    { category: "时间", zh: "今天", ar: "اليوم", rom: "al-yawm" },
    { category: "时间", zh: "明天", ar: "غدا", rom: "ghadan" },
    { category: "时间", zh: "昨天", ar: "أمس", rom: "ams" },
    { category: "时间", zh: "现在", ar: "الآن", rom: "al-an" },
    { category: "时间", zh: "早上", ar: "صباحا", rom: "sabahan" },
    { category: "时间", zh: "晚上", ar: "مساء", rom: "masaan" },
    { category: "颜色", zh: "红色", ar: "أحمر", rom: "ahmar" },
    { category: "颜色", zh: "蓝色", ar: "أزرق", rom: "azraq" },
    { category: "颜色", zh: "绿色", ar: "أخضر", rom: "akhdar" },
    { category: "颜色", zh: "黄色", ar: "أصفر", rom: "asfar" },
    { category: "颜色", zh: "黑色", ar: "أسود", rom: "aswad" },
    { category: "颜色", zh: "白色", ar: "أبيض", rom: "abyad" }
  ];

  const nouns = [
    ["水", "ماء", "ma"],
    ["牛奶", "حليب", "halib"],
    ["果汁", "عصير", "asir"],
    ["面包", "خبز", "khubz"],
    ["米饭", "أرز", "aruzz"],
    ["苹果", "تفاح", "tuffah"],
    ["香蕉", "موز", "mawz"],
    ["书", "كتاب", "kitab"],
    ["笔", "قلم", "qalam"],
    ["包", "حقيبة", "haqiba"],
    ["球", "كرة", "kura"],
    ["票", "تذكرة", "tadhkira"],
    ["钥匙", "مفتاح", "miftah"],
    ["手机", "هاتف", "hatif"],
    ["鞋子", "حذاء", "hidha"],
    ["帽子", "قبعة", "qubaa"],
    ["椅子", "كرسي", "kursi"],
    ["桌子", "طاولة", "tawila"],
    ["门", "باب", "bab"],
    ["窗户", "نافذة", "nafitha"],
    ["学校", "المدرسة", "al-madrasa"],
    ["家", "البيت", "al-bayt"],
    ["餐厅", "المطعم", "al-matam"],
    ["商店", "المتجر", "al-matjar"],
    ["公园", "الحديقة", "al-hadiqa"],
    ["医院", "المستشفى", "al-mustashfa"],
    ["机场", "المطار", "al-matar"],
    ["图书馆", "المكتبة", "al-maktaba"],
    ["厕所", "الحمام", "al-hammam"],
    ["海滩", "الشاطئ", "ash-shati"]
  ];

  const templates = [
    ["我想要{zh}", "أريد {ar}", "urid {rom}", "日常表达"],
    ["我需要{zh}", "أحتاج {ar}", "ahtaj {rom}", "日常表达"],
    ["我喜欢{zh}", "أحب {ar}", "uhibb {rom}", "日常表达"],
    ["我不喜欢{zh}", "لا أحب {ar}", "la uhibb {rom}", "日常表达"],
    ["请给我{zh}", "من فضلك أعطني {ar}", "min fadlik atini {rom}", "日常表达"],
    ["{zh}在哪里？", "أين {ar}؟", "ayna {rom}", "地点问答"],
    ["你有{zh}吗？", "هل عندك {ar}؟", "hal indaka {rom}", "购物问答"]
  ];

  const generated = templates.flatMap(([zhTemplate, arTemplate, romTemplate, category]) =>
    nouns.map(([zh, ar, rom]) => ({
      category,
      zh: zhTemplate.replace("{zh}", zh),
      ar: arTemplate.replace("{ar}", ar),
      rom: romTemplate.replace("{rom}", rom)
    }))
  );

  const seen = new Set();
  return [...core, ...generated].filter((item) => {
    const key = `${item.zh}|${item.ar}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
})();
