window.dailyArabicQuestionBank = [
  { category: "问候", zh: "你好", ar: "مرحبا", rom: "marhaban" },
  { category: "问候", zh: "愿你平安", ar: "السلام عليكم", rom: "as-salamu alaykum" },
  { category: "问候", zh: "也愿你平安", ar: "وعليكم السلام", rom: "wa alaykum as-salam" },
  { category: "问候", zh: "早上好", ar: "صباح الخير", rom: "sabah al-khayr" },
  { category: "问候", zh: "晚上好", ar: "مساء الخير", rom: "masa al-khayr" },
  { category: "问候", zh: "晚安", ar: "تصبح على خير", rom: "tusbih ala khayr" },
  { category: "问候", zh: "你好吗？", ar: "كيف حالك؟", rom: "kayfa haluka" },
  { category: "问候", zh: "我很好", ar: "أنا بخير", rom: "ana bikhayr" },
  { category: "问候", zh: "你呢？", ar: "وأنت؟", rom: "wa anta" },
  { category: "问候", zh: "很高兴见到你", ar: "سعيد بلقائك", rom: "saeed biliqaik" },
  { category: "问候", zh: "明天见", ar: "أراك غدا", rom: "araka ghadan" },
  { category: "问候", zh: "再见", ar: "مع السلامة", rom: "ma'a as-salamah" },

  { category: "礼貌用语", zh: "谢谢", ar: "شكرا", rom: "shukran" },
  { category: "礼貌用语", zh: "非常感谢", ar: "شكرا جزيلا", rom: "shukran jazilan" },
  { category: "礼貌用语", zh: "不客气", ar: "عفوا", rom: "afwan" },
  { category: "礼貌用语", zh: "请", ar: "من فضلك", rom: "min fadlik" },
  { category: "礼貌用语", zh: "对不起", ar: "آسف", rom: "asif" },
  { category: "礼貌用语", zh: "没关系", ar: "لا مشكلة", rom: "la mushkila" },
  { category: "礼貌用语", zh: "可以吗？", ar: "هل يمكن؟", rom: "hal yumkin" },
  { category: "礼貌用语", zh: "当然可以", ar: "نعم بالتأكيد", rom: "na'am bit-takid" },
  { category: "礼貌用语", zh: "请等一下", ar: "انتظر قليلا", rom: "intazir qalilan" },
  { category: "礼貌用语", zh: "请再说一遍", ar: "كرر من فضلك", rom: "karrir min fadlik" },
  { category: "礼貌用语", zh: "我不明白", ar: "أنا لا أفهم", rom: "ana la afham" },
  { category: "礼貌用语", zh: "请慢一点说", ar: "تكلم ببطء من فضلك", rom: "takallam bibut min fadlik" },

  { category: "介绍自己", zh: "我叫小西", ar: "اسمي شيشي", rom: "ismi xixi" },
  { category: "介绍自己", zh: "你叫什么名字？", ar: "ما اسمك؟", rom: "ma ismuka" },
  { category: "介绍自己", zh: "我来自中国", ar: "أنا من الصين", rom: "ana min as-sin" },
  { category: "介绍自己", zh: "我住在阿布扎比", ar: "أنا أسكن في أبوظبي", rom: "ana askun fi abu dhabi" },
  { category: "介绍自己", zh: "我七岁", ar: "عمري سبع سنوات", rom: "umri saba sanawat" },
  { category: "介绍自己", zh: "我十岁", ar: "عمري عشر سنوات", rom: "umri ashr sanawat" },
  { category: "介绍自己", zh: "我是学生", ar: "أنا طالب", rom: "ana talib" },
  { category: "介绍自己", zh: "这是我的朋友", ar: "هذا صديقي", rom: "hadha sadiqi" },
  { category: "介绍自己", zh: "这是我的家人", ar: "هذه عائلتي", rom: "hadhihi ailati" },
  { category: "介绍自己", zh: "我的学校在这里", ar: "مدرستي هنا", rom: "madrasati huna" },

  { category: "学校", zh: "我要去学校", ar: "أذهب إلى المدرسة", rom: "adhhab ila al-madrasa" },
  { category: "学校", zh: "我在学校", ar: "أنا في المدرسة", rom: "ana fi al-madrasa" },
  { category: "学校", zh: "我的老师很好", ar: "معلمي لطيف", rom: "muallimi latif" },
  { category: "学校", zh: "这是我的书", ar: "هذا كتابي", rom: "hadha kitabi" },
  { category: "学校", zh: "这是我的笔", ar: "هذا قلمي", rom: "hadha qalami" },
  { category: "学校", zh: "我忘了作业", ar: "نسيت الواجب", rom: "nasitu al-wajib" },
  { category: "学校", zh: "我完成了作业", ar: "أنهيت الواجب", rom: "anhaytu al-wajib" },
  { category: "学校", zh: "我喜欢数学", ar: "أحب الرياضيات", rom: "uhibb ar-riyadiyat" },
  { category: "学校", zh: "我喜欢科学", ar: "أحب العلوم", rom: "uhibb al-ulum" },
  { category: "学校", zh: "我可以去厕所吗？", ar: "هل أستطيع الذهاب إلى الحمام؟", rom: "hal astati adh-dhahab ila al-hammam" },
  { category: "学校", zh: "请帮我", ar: "ساعدني من فضلك", rom: "sa'idni min fadlik" },
  { category: "学校", zh: "我有一个问题", ar: "عندي سؤال", rom: "indi sual" },
  { category: "学校", zh: "我可以借一支笔吗？", ar: "هل أستعير قلما؟", rom: "hal asta'ir qalaman" },
  { category: "学校", zh: "上课开始了", ar: "بدأ الدرس", rom: "bada ad-dars" },
  { category: "学校", zh: "下课了", ar: "انتهى الدرس", rom: "intaha ad-dars" },

  { category: "问路", zh: "请问厕所在哪里？", ar: "أين الحمام من فضلك؟", rom: "ayna al-hammam min fadlik" },
  { category: "问路", zh: "学校在哪里？", ar: "أين المدرسة؟", rom: "ayna al-madrasa" },
  { category: "问路", zh: "商店在哪里？", ar: "أين المتجر؟", rom: "ayna al-matjar" },
  { category: "问路", zh: "餐厅在哪里？", ar: "أين المطعم؟", rom: "ayna al-matam" },
  { category: "问路", zh: "公园在哪里？", ar: "أين الحديقة؟", rom: "ayna al-hadiqa" },
  { category: "问路", zh: "医院在哪里？", ar: "أين المستشفى؟", rom: "ayna al-mustashfa" },
  { category: "问路", zh: "机场在哪里？", ar: "أين المطار؟", rom: "ayna al-matar" },
  { category: "问路", zh: "图书馆在哪里？", ar: "أين المكتبة؟", rom: "ayna al-maktaba" },
  { category: "问路", zh: "这里远吗？", ar: "هل هو بعيد؟", rom: "hal huwa baid" },
  { category: "问路", zh: "这里近吗？", ar: "هل هو قريب؟", rom: "hal huwa qarib" },
  { category: "问路", zh: "请向左走", ar: "اذهب يسارا من فضلك", rom: "idhhab yasaran min fadlik" },
  { category: "问路", zh: "请向右走", ar: "اذهب يمينا من فضلك", rom: "idhhab yaminan min fadlik" },
  { category: "问路", zh: "一直往前走", ar: "اذهب إلى الأمام", rom: "idhhab ila al-amam" },
  { category: "问路", zh: "我迷路了", ar: "أنا تائه", rom: "ana taih" },
  { category: "问路", zh: "我想回家", ar: "أريد أن أعود إلى البيت", rom: "urid an aud ila al-bayt" },

  { category: "买东西", zh: "多少钱？", ar: "كم السعر؟", rom: "kam as-sir" },
  { category: "买东西", zh: "这个多少钱？", ar: "بكم هذا؟", rom: "bikam hadha" },
  { category: "买东西", zh: "我想买这个", ar: "أريد أن أشتري هذا", rom: "urid an ashtari hadha" },
  { category: "买东西", zh: "我只是看看", ar: "أنا فقط أنظر", rom: "ana faqat anzur" },
  { category: "买东西", zh: "太贵了", ar: "هذا غال جدا", rom: "hadha ghal jiddan" },
  { category: "买东西", zh: "有小一点的吗？", ar: "هل يوجد أصغر؟", rom: "hal yujad asghar" },
  { category: "买东西", zh: "有大一点的吗？", ar: "هل يوجد أكبر؟", rom: "hal yujad akbar" },
  { category: "买东西", zh: "有红色的吗？", ar: "هل يوجد باللون الأحمر؟", rom: "hal yujad bil-lawn al-ahmar" },
  { category: "买东西", zh: "我需要一个袋子", ar: "أحتاج كيسا", rom: "ahtaj kisan" },
  { category: "买东西", zh: "可以刷卡吗？", ar: "هل أستطيع الدفع بالبطاقة؟", rom: "hal astati ad-daf bil-bitaqa" },
  { category: "买东西", zh: "我要付现金", ar: "سأدفع نقدا", rom: "saadfa naqdan" },
  { category: "买东西", zh: "请给我收据", ar: "أعطني الإيصال من فضلك", rom: "atini al-iyssal min fadlik" },

  { category: "餐厅", zh: "菜单在哪里？", ar: "أين القائمة؟", rom: "ayna al-qaimah" },
  { category: "餐厅", zh: "我想点这个", ar: "أريد هذا", rom: "urid hadha" },
  { category: "餐厅", zh: "请给我水", ar: "أعطني ماء من فضلك", rom: "atini ma min fadlik" },
  { category: "餐厅", zh: "我想喝果汁", ar: "أريد عصيرا", rom: "urid asiran" },
  { category: "餐厅", zh: "我想吃鸡肉", ar: "أريد دجاجا", rom: "urid dajajan" },
  { category: "餐厅", zh: "我不吃辣", ar: "لا آكل الحار", rom: "la akul al-har" },
  { category: "餐厅", zh: "不要洋葱", ar: "بدون بصل", rom: "bidun basal" },
  { category: "餐厅", zh: "请少一点盐", ar: "ملح قليل من فضلك", rom: "milh qalil min fadlik" },
  { category: "餐厅", zh: "请快一点", ar: "بسرعة من فضلك", rom: "bisura min fadlik" },
  { category: "餐厅", zh: "账单请给我", ar: "الحساب من فضلك", rom: "al-hisab min fadlik" },
  { category: "餐厅", zh: "食物很好吃", ar: "الطعام لذيذ", rom: "at-taam ladhidh" },
  { category: "餐厅", zh: "谢谢，吃饱了", ar: "شكرا شبعت", rom: "shukran shabitu" },

  { category: "形容食物", zh: "好吃", ar: "لذيذ", rom: "ladhidh" },
  { category: "形容食物", zh: "甜的", ar: "حلو", rom: "hilw" },
  { category: "形容食物", zh: "辣的", ar: "حار", rom: "har" },
  { category: "形容食物", zh: "咸的", ar: "مالح", rom: "malih" },
  { category: "形容食物", zh: "酸的", ar: "حامض", rom: "hamid" },
  { category: "形容食物", zh: "热的", ar: "ساخن", rom: "sakhin" },
  { category: "形容食物", zh: "冷的", ar: "بارد", rom: "barid" },
  { category: "形容食物", zh: "新鲜的", ar: "طازج", rom: "tazaj" },
  { category: "形容食物", zh: "这个太辣了", ar: "هذا حار جدا", rom: "hadha har jiddan" },
  { category: "形容食物", zh: "这个太甜了", ar: "هذا حلو جدا", rom: "hadha hilw jiddan" },
  { category: "形容食物", zh: "这个有点冷", ar: "هذا بارد قليلا", rom: "hadha barid qalilan" },
  { category: "形容食物", zh: "我喜欢这个味道", ar: "أحب هذا الطعم", rom: "uhibb hadha at-tam" },

  { category: "交朋友", zh: "我们可以做朋友吗？", ar: "هل نكون أصدقاء؟", rom: "hal nakun asdiqa" },
  { category: "交朋友", zh: "你想一起玩吗？", ar: "هل تريد أن نلعب معا؟", rom: "hal turid an nalab maan" },
  { category: "交朋友", zh: "你喜欢什么游戏？", ar: "ما لعبتك المفضلة؟", rom: "ma lubatuka al-mufaddala" },
  { category: "交朋友", zh: "我喜欢这个游戏", ar: "أحب هذه اللعبة", rom: "uhibb hadhihi al-luba" },
  { category: "交朋友", zh: "来这里", ar: "تعال هنا", rom: "taal huna" },
  { category: "交朋友", zh: "轮到你了", ar: "دورك الآن", rom: "dawruka al-an" },
  { category: "交朋友", zh: "轮到我了", ar: "دوري الآن", rom: "dawri al-an" },
  { category: "交朋友", zh: "你赢了", ar: "أنت فزت", rom: "anta fuzta" },
  { category: "交朋友", zh: "我赢了", ar: "أنا فزت", rom: "ana fuztu" },
  { category: "交朋友", zh: "没关系，再来一次", ar: "لا مشكلة مرة أخرى", rom: "la mushkila marra ukhra" },
  { category: "交朋友", zh: "我们一起跑吧", ar: "لنركض معا", rom: "lanarkud maan" },
  { category: "交朋友", zh: "我们一起画画吧", ar: "لنرسم معا", rom: "lanarsum maan" },
  { category: "交朋友", zh: "我们一起读书吧", ar: "لنقرأ معا", rom: "lanaqra maan" },
  { category: "交朋友", zh: "你是我的好朋友", ar: "أنت صديقي الجيد", rom: "anta sadiqi al-jayyid" },
  { category: "交朋友", zh: "我很开心和你玩", ar: "أنا سعيد باللعب معك", rom: "ana saeed bil-laib maak" },

  { category: "心情", zh: "我很开心", ar: "أنا سعيد", rom: "ana saeed" },
  { category: "心情", zh: "我有点累", ar: "أنا متعب قليلا", rom: "ana mutab qalilan" },
  { category: "心情", zh: "我饿了", ar: "أنا جائع", rom: "ana jai" },
  { category: "心情", zh: "我渴了", ar: "أنا عطشان", rom: "ana atshan" },
  { category: "心情", zh: "我很兴奋", ar: "أنا متحمس", rom: "ana mutahammis" },
  { category: "心情", zh: "我有点害怕", ar: "أنا خائف قليلا", rom: "ana khaif qalilan" },
  { category: "心情", zh: "我很忙", ar: "أنا مشغول", rom: "ana mashghul" },
  { category: "心情", zh: "我准备好了", ar: "أنا جاهز", rom: "ana jahiz" },

  { category: "日常动作", zh: "我想喝水", ar: "أريد أن أشرب ماء", rom: "urid an ashrab ma" },
  { category: "日常动作", zh: "我想吃饭", ar: "أريد أن آكل", rom: "urid an akul" },
  { category: "日常动作", zh: "我想回家", ar: "أريد أن أعود إلى البيت", rom: "urid an aud ila al-bayt" },
  { category: "日常动作", zh: "我想睡觉", ar: "أريد أن أنام", rom: "urid an anam" },
  { category: "日常动作", zh: "我想休息", ar: "أريد أن أرتاح", rom: "urid an artah" },
  { category: "日常动作", zh: "我要洗手", ar: "أريد أن أغسل يدي", rom: "urid an aghsil yaday" },
  { category: "日常动作", zh: "我要打电话", ar: "أريد أن أتصل", rom: "urid an attasil" },
  { category: "日常动作", zh: "我找不到我的包", ar: "لا أجد حقيبتي", rom: "la ajid haqibati" },
  { category: "日常动作", zh: "请打开门", ar: "افتح الباب من فضلك", rom: "iftah al-bab min fadlik" },
  { category: "日常动作", zh: "请关上门", ar: "أغلق الباب من فضلك", rom: "aghliq al-bab min fadlik" },
  { category: "日常动作", zh: "我们走吧", ar: "هيا بنا", rom: "hayya bina" },
  { category: "日常动作", zh: "快点", ar: "أسرع", rom: "asri" }
];
