(function(){var p,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function r(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
var ea=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if(typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){e===void 0&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}(),fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ka={};try{ka.__proto__=ia;ha=ka.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=fa;
function u(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ka=b.prototype}function ma(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ma(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function na(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function x(){this.u=!1;this.l=null;this.o=void 0;this.g=1;this.i=this.m=0;this.A=this.h=null}
function oa(a){if(a.u)throw new TypeError("Generator is already running");a.u=!0}x.prototype.C=function(a){this.o=a};function pa(a,b){a.h={ba:b,da:!0};a.g=a.m||a.i}x.prototype.getNextAddressJsc=function(){return this.g};x.prototype.getYieldResultJsc=function(){return this.o};x.prototype.return=function(a){this.h={return:a};this.g=this.i};x.prototype["return"]=x.prototype.return;x.prototype.K=function(a){this.h={F:a};this.g=this.i};x.prototype.jumpThroughFinallyBlocks=x.prototype.K;
x.prototype.v=function(a,b){this.g=b;return{value:a}};x.prototype.yield=x.prototype.v;x.prototype.S=function(a,b){a=v(a);var c=a.next();na(c);if(c.done)this.o=c.value,this.g=b;else return this.l=a,this.v(c.value,b)};x.prototype.yieldAll=x.prototype.S;x.prototype.F=function(a){this.g=a};x.prototype.jumpTo=x.prototype.F;x.prototype.D=function(){this.g=0};x.prototype.jumpToEnd=x.prototype.D;x.prototype.P=function(a,b){this.m=a;b!=void 0&&(this.i=b)};x.prototype.setCatchFinallyBlocks=x.prototype.P;
x.prototype.R=function(a){this.m=0;this.i=a||0};x.prototype.setFinallyBlock=x.prototype.R;x.prototype.O=function(a,b){this.g=a;this.m=b||0};x.prototype.leaveTryBlock=x.prototype.O;x.prototype.H=function(a){this.m=a||0;a=this.h.ba;this.h=null;return a};x.prototype.enterCatchBlock=x.prototype.H;x.prototype.I=function(a,b,c){c?this.A[c]=this.h:this.A=[this.h];this.m=a||0;this.i=b||0};x.prototype.enterFinallyBlock=x.prototype.I;
x.prototype.N=function(a,b){b=this.A.splice(b||0)[0];(b=this.h=this.h||b)?b.da?this.g=this.m||this.i:b.F!=void 0&&this.i<b.F?(this.g=b.F,this.h=null):this.g=this.i:this.g=a};x.prototype.leaveFinallyBlock=x.prototype.N;x.prototype.J=function(a){return new qa(a)};x.prototype.forIn=x.prototype.J;function qa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}qa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
qa.prototype.getNext=qa.prototype.h;function sa(a){this.g=new x;this.h=a}function ua(a,b){oa(a.g);var c=a.g.l;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.g.l,c);na(e);if(!e.done)return a.g.u=!1,e;var k=e.value}catch(f){return a.g.l=null,pa(a.g,f),wa(a)}a.g.l=null;d.call(a.g,k);return wa(a)}
function wa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.u=!1,{value:b.value,done:!1}}catch(c){a.g.o=void 0,pa(a.g,c)}a.g.u=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.da)throw b.ba;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){oa(a.g);a.g.l?b=va(a,a.g.l.next,b,a.g.C):(a.g.C(b),b=wa(a));return b};this.throw=function(b){oa(a.g);a.g.l?b=va(a,a.g.l["throw"],b,a.g.C):(pa(a.g,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function k(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(k,e)}k(a.next())})}
function za(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}r("Reflect",function(a){return a?a:{}});r("Reflect.construct",function(){return ea});r("Reflect.setPrototypeOf",function(a){return a?a:la?function(b,c){try{return la(b,c),!0}catch(d){return!1}}:null});
r("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,f){this.g=k;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Aa(ma(this))}});return a});function Aa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.u=!1;var g=this.l();try{f(g.resolve,g.reject)}catch(h){g.reject(h)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.m()})}this.g.push(f)};var e=da.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var h=
f[g];f[g]=null;try{h()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(f){this.i(function(){throw f;})};b.prototype.l=function(){function f(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;return{resolve:f(this.H),reject:f(this.m)}};b.prototype.H=function(f){if(f===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.J(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.D(f):this.o(f)}};
b.prototype.D=function(f){var g=void 0;try{g=f.then}catch(h){this.m(h);return}typeof g=="function"?this.K(g,f):this.o(f)};b.prototype.m=function(f){this.v(2,f)};b.prototype.o=function(f){this.v(1,f)};b.prototype.v=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.i=g;this.h===2&&this.I();this.C()};b.prototype.I=function(){var f=this;e(function(){if(f.A()){var g=da.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var f=da.CustomEvent,g=da.Event,h=da.dispatchEvent;if(typeof h==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=da.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return h(f)};b.prototype.C=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)k.h(this.g[f]);this.g=null}};var k=new c;
b.prototype.J=function(f){var g=this.l();f.U(g.resolve,g.reject)};b.prototype.K=function(f,g){var h=this.l();try{f.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};b.prototype.then=function(f,g){function h(q,t){return typeof q=="function"?function(y){try{l(q(y))}catch(B){m(B)}}:t}var l,m,n=new b(function(q,t){l=q;m=t});this.U(h(f,l),h(g,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.U=function(f,g){function h(){switch(l.h){case 1:f(l.i);break;case 2:g(l.i);break;
default:throw Error("Unexpected state: "+l.h);}}var l=this;this.g==null?k.h(h):this.g.push(h);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(g,h){h(f)})};b.race=function(f){return new b(function(g,h){for(var l=v(f),m=l.next();!m.done;m=l.next())d(m.value).U(g,h)})};b.all=function(f){var g=v(f),h=g.next();return h.done?d([]):new b(function(l,m){function n(y){return function(B){q[y]=B;t--;t==0&&l(q)}}var q=[],t=0;do q.push(void 0),t++,d(h.value).U(n(q.length-1),m),h=g.next();while(!h.done)})};
return b});r("Object.setPrototypeOf",function(a){return a||la});function Ba(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return Ba(this,function(b){return b})}});
r("WeakMap",function(a){function b(h){this.g=(g+=Math.random()+1).toString();if(h){h=v(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function e(h){if(!w(h,f)){var l=new c;ba(h,f,{value:l})}}function k(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var g=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");e(h);if(!w(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=l;return this};b.prototype.get=function(h){return d(h)&&w(h,f)?h[f][this.g]:void 0};b.prototype.has=function(h){return d(h)&&w(h,
f)&&w(h[f],this.g)};b.prototype.delete=function(h){return d(h)&&w(h,f)&&w(h[f],this.g)?delete h[f][this.g]:!1};return b});
r("Map",function(a){function b(){var g={};return g.B=g.next=g.head=g}function c(g,h){var l=g[1];return Aa(function(){if(l){for(;l.head!=g[1];)l=l.B;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(g,h){var l=h&&typeof h;l=="object"||l=="function"?k.has(h)?l=k.get(h):(l=""+ ++f,k.set(h,l)):l="p_"+h;var m=g[0][l];if(m&&w(g[0],l))for(g=0;g<m.length;g++){var n=m[g];if(h!==h&&n.key!==n.key||h===n.key)return{id:l,list:m,index:g,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=v(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),h=new a(v([[g,"s"]]));if(h.get(g)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(g,h){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=h:(l.entry={next:this[1],B:this[1].B,head:this[1],key:g,value:h},l.list.push(l.entry),this[1].B.next=l.entry,this[1].B=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.B.next=g.entry.next,
g.entry.next.B=g.entry.B,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].B=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=
function(g,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(h,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});r("Array.prototype.entries",function(a){return a?a:function(){return Ba(this,function(b,c){return[b,c]})}});r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}});r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}});
r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],k=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof k=="function"){b=k.call(b);for(var f=0;!(k=b.next()).done;)e.push(c.call(d,k.value,f++))}else for(k=b.length,f=0;f<k;f++)e.push(c.call(d,b[f],f));return e}});
r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});r("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});r("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});r("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
r("String.prototype.startsWith",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var k=0;k<e&&c<d;)if(this[c++]!=b[k++])return!1;return k>=e}});
r("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});r("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});r("Array.prototype.values",function(a){return a?a:function(){return Ba(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var z=this||self;function Ca(a){var b=za.apply(1,arguments).filter(Boolean).join("&");if(!b)return a;var c=a.match(/[?&]adurl=/);return c?a.slice(0,c.index+1)+b+"&"+a.slice(c.index+1):a+(a.indexOf("?")<0?"?":"&")+b}function Da(a,b){return a===0?"ri=1":a===1?b?"ri=24":"ri=27":a===2?b?"ri=25":"ri=26":""}function Ea(a,b){return b?"&"+a+"="+encodeURIComponent(b):""}
function Fa(a){var b=a.url;a=a.sa;this.h=b;this.l=a;this.i=(new Date).getTime()-17040672E5;this.g={};for(var c=/[?&]([^&=]+)=([^&]*)/g;a=c.exec(b);)this.g[a[1]]=a[2]}function Ga(a,b){if(a.g.dsh==="1")return null;var c=a.g.ae;if(c==="1"){var d=a.g.adurl;if(d)try{return{version:3,V:decodeURIComponent(d),T:Ca(a.h,"act=1",Da(b,!0),Ha(a))}}catch(e){}}return c==="2"?{version:4,V:Ca(a.h,"dct=1","suid="+a.i,Da(b,!1)),T:Ca(a.h,"act=1",Da(b,!0),"suid="+a.i)}:null}
function Ia(a,b){return b===2?Ca(a.h,"ri=2"):b===0?Ca(a.h,"ri=16"):a.h}function Ha(a){a=a.l;if(!a)return"";var b=Ea("uap",a.platform)+Ea("uapv",a.platformVersion)+Ea("uafv",a.uaFullVersion)+Ea("uaa",a.architecture)+Ea("uam",a.model)+Ea("uab",a.bitness);a.fullVersionList&&(b+="&uafvl="+encodeURIComponent(a.fullVersionList.map(function(c){return encodeURIComponent(c.brand)+";"+encodeURIComponent(c.version)}).join("|")));a.wow64!=null&&(b+="&uaw="+Number(a.wow64));return b.slice(1)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function Ja(a){this.g=a}Ja.prototype.toString=function(){return this.g};var Ka=new Ja("about:invalid#zClosurez");function La(a){this.ra=a}function A(a){return new La(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ma=new La(function(a){return/^[^:]*([/?#]|$)/.test(a)}),Na=A("http"),Oa=A("https"),Pa=A("ftp"),Qa=A("mailto"),Ra=A("intent"),Sa=A("market"),Ta=A("itms"),Ua=A("itms-appss"),Va=[A("data"),Na,Oa,Qa,Pa,Ma],Wa=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Xa(a,b){if(b instanceof Ja)if(b instanceof Ja)b=b.g;else throw Error("");else b=Wa.test(b)?b:void 0;b!==void 0&&(a.href=b)};var Ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Za=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function $a(a,b){a:{for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return b<0?null:typeof a==="string"?a.charAt(b):a[b]};function ab(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function bb(a){z.setTimeout(function(){throw a;},0)};function cb(a){var b;a:{if(b=z.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};var db,eb;a:{for(var fb=["CLOSURE_FLAGS"],gb=z,ib=0;ib<fb.length;ib++)if(gb=gb[fb[ib]],gb==null){eb=null;break a}eb=gb}var jb=eb&&eb[748402147];db=jb!=null?jb:!0;function kb(){return cb("iPhone")&&!cb("iPod")&&!cb("iPad")};function lb(a){lb[" "](a);return a}lb[" "]=function(){};var nb=kb(),ob=cb("iPad");var pb=kb()||cb("iPod"),qb=cb("iPad");var rb={},sb=null;var tb=void 0;function ub(a){a=Error(a);ab(a,"warning");return a};function vb(){return typeof BigInt==="function"};var wb=typeof Symbol==="function"&&typeof Symbol()==="symbol";function xb(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var yb=xb("jas",void 0,!0),zb=xb(void 0,"0di"),Ab=xb(void 0,"0actk"),Bb=xb("m_m","Ja",!0);var Cb={qa:{value:0,configurable:!0,writable:!0,enumerable:!1}},Db=Object.defineProperties,C=wb?yb:"qa",Eb,Fb=[];E(Fb,7);Eb=Object.freeze(Fb);function Gb(a,b){wb||C in a||Db(a,Cb);a[C]|=b}function E(a,b){wb||C in a||Db(a,Cb);a[C]=b}function Hb(a){Gb(a,34);return a}function Ib(a){Gb(a,8192);return a};var Jb={};function F(a,b){return b===void 0?a.g!==Kb&&!!(2&(a.j[C]|0)):!!(2&b)&&a.g!==Kb}var Kb={};function Lb(a,b,c){this.g=a;this.h=b;this.i=c}Lb.prototype.next=function(){var a=this.g.next();a.done||(a.value=this.h.call(this.i,a.value));return a};Lb.prototype[Symbol.iterator]=function(){return this};var Mb=Object.freeze({});function Nb(a){a.Ia=!0;return a};var Ob=Nb(function(a){return typeof a==="number"}),Pb=Nb(function(a){return typeof a==="string"}),Qb=Nb(function(a){return typeof a==="boolean"}),Rb=Nb(function(a){return typeof a==="function"});var Sb=typeof z.BigInt==="function"&&typeof z.BigInt(0)==="bigint";function Tb(a){var b=a;if(Pb(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ob(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Sb?BigInt(a):a=Qb(a)?a?"1":"0":Pb(a)?a.trim()||"0":String(a)}var Zb=Nb(function(a){return Sb?a>=Ub&&a<=Vb:a[0]==="-"?Wb(a,Xb):Wb(a,Yb)}),Xb=Number.MIN_SAFE_INTEGER.toString(),Ub=Sb?BigInt(Number.MIN_SAFE_INTEGER):void 0,Yb=Number.MAX_SAFE_INTEGER.toString(),Vb=Sb?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Wb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var G=0,H=0;function $b(a){var b=a>>>0;G=b;H=(a-b)/4294967296>>>0}function ac(a){if(a<0){$b(-a);var b=v(bc(G,H));a=b.next().value;b=b.next().value;G=a>>>0;H=b>>>0}else $b(a)}function cc(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else vb()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+dc(c)+dc(a));return c}
function dc(a){a=String(a);return"0000000".slice(a.length)+a}function ec(){var a=G,b=H;b&2147483648?vb()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=v(bc(a,b)),a=b.next().value,b=b.next().value,a="-"+cc(a,b)):a=cc(a,b);return a}function bc(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function fc(a){return Array.prototype.slice.call(a)};var hc=typeof BigInt==="function"?BigInt.asIntN:void 0,ic=Number.isSafeInteger,jc=Number.isFinite,kc=Math.trunc,lc=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function mc(a){switch(typeof a){case "bigint":return!0;case "number":return jc(a);case "string":return lc.test(a);default:return!1}}function nc(a){if(!jc(a))throw ub("enum");return a|0}function oc(a){return a==null?a:jc(a)?a|0:void 0}function pc(a){if(typeof a!=="number")throw ub("int32");if(!jc(a))throw ub("int32");return a|0}
function qc(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return jc(a)?a|0:void 0}function rc(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return jc(a)?a>>>0:void 0}
function vc(a){var b=void 0;b!=null||(b=1024);if(!mc(a))throw ub("int64");var c=typeof a;switch(b){case 512:switch(c){case "string":return wc(a);case "bigint":return String(hc(64,a));default:return xc(a)}case 1024:switch(c){case "string":return b=kc(Number(a)),ic(b)?a=Tb(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a=vb()?Tb(hc(64,BigInt(a))):Tb(yc(a))),a;case "bigint":return Tb(hc(64,a));default:return ic(a)?Tb(zc(a)):Tb(xc(a))}case 0:switch(c){case "string":return wc(a);case "bigint":return Tb(hc(64,
a));default:return zc(a)}default:throw Error("Unknown format requested type for int64");}}
function yc(a){var b=a.length;if(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")return a;if(a.length<16)ac(Number(a));else if(vb())a=BigInt(a),G=Number(a&BigInt(4294967295))>>>0,H=Number(a>>BigInt(32)&BigInt(4294967295));else{b=+(a[0]==="-");H=G=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),H*=1E6,G=G*1E6+d,G>=4294967296&&(H+=Math.trunc(G/4294967296),H>>>=0,G>>>=0);b&&(b=v(bc(G,H)),a=b.next().value,b=b.next().value,G=a,H=b)}return ec()}
function zc(a){a=kc(a);if(!ic(a)){ac(a);var b=G,c=H;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);var d=c*4294967296+(b>>>0);b=Number.isSafeInteger(d)?d:cc(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}function xc(a){a=kc(a);ic(a)?a=String(a):(ac(a),a=ec());return a}function wc(a){var b=kc(Number(a));if(ic(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return yc(a)}function I(a){return a==null||typeof a==="string"?a:void 0}
function Ac(a,b,c,d){if(a!=null&&a[Bb]===Jb)return a;if(!Array.isArray(a))return c?d&2?((a=b[zb])||(a=new b,Hb(a.j),a=b[zb]=a),b=a):b=new b:b=void 0,b;c=a[C]|0;d=c|d&32|d&2;d!==c&&E(a,d);return new b(a)}function Bc(a,b,c){a=b?pc(a):qc(a);return a==null?c?0:void 0:a|0}function J(a,b,c){if(b){if(typeof a!=="string")throw Error();return a}var d;return(d=I(a))!=null?d:c?"":void 0};function Cc(a){return a};var Dc={},Ec=function(){try{var a=function(){return ea(Map,[],this.constructor)};u(a,Map);lb(new a);return!1}catch(b){return!0}}();function Fc(){this.g=new Map}p=Fc.prototype;p.get=function(a){return this.g.get(a)};p.set=function(a,b){this.g.set(a,b);this.size=this.g.size;return this};p.delete=function(a){a=this.g.delete(a);this.size=this.g.size;return a};p.clear=function(){this.g.clear();this.size=this.g.size};p.has=function(a){return this.g.has(a)};p.entries=function(){return this.g.entries()};
p.keys=function(){return this.g.keys()};p.values=function(){return this.g.values()};p.forEach=function(a,b){return this.g.forEach(a,b)};Fc.prototype[Symbol.iterator]=function(){return this.entries()};var K=function(){function a(){return ea(Map,[],this.constructor)}if(Ec)return Object.setPrototypeOf(Fc.prototype,Map.prototype),Object.defineProperties(Fc.prototype,{size:{value:0,configurable:!0,enumerable:!0,writable:!0}}),Fc;u(a,Map);return a}();function Gc(a){return a}
function L(a,b,c,d){c=c===void 0?Gc:c;d=d===void 0?Gc:d;var e=K.call(this)||this;e.L=a[C]|0;e.G=b;e.W=c;e.fa=e.G?Hc:d;for(var k=0;k<a.length;k++){var f=a[k],g=c(f[0],!1,!0),h=f[1];b?h===void 0&&(h=null):h=d(f[1],!1,!0,void 0,void 0,e.L);K.prototype.set.call(e,g,h)}return e}u(L,K);function Ic(a){if(a.L&2)throw Error("Cannot mutate an immutable Map");}function Jc(a,b){return Ib(Array.from(K.prototype.entries.call(a),b))}p=L.prototype;p.clear=function(){Ic(this);K.prototype.clear.call(this)};
p.delete=function(a){Ic(this);return K.prototype.delete.call(this,this.W(a,!0,!1))};p.entries=function(){if(this.G){var a=K.prototype.keys.call(this);a=new Lb(a,Kc,this)}else a=K.prototype.entries.call(this);return a};p.values=function(){if(this.G){var a=K.prototype.keys.call(this);a=new Lb(a,L.prototype.get,this)}else a=K.prototype.values.call(this);return a};p.forEach=function(a,b){this.G?K.prototype.forEach.call(this,function(c,d,e){a.call(b,e.get(d),d,e)}):K.prototype.forEach.call(this,a,b)};
p.set=function(a,b){Ic(this);a=this.W(a,!0,!1);return a==null?this:b==null?(K.prototype.delete.call(this,a),this):K.prototype.set.call(this,a,this.fa(b,!0,!0,this.G,!1,this.L))};p.has=function(a){return K.prototype.has.call(this,this.W(a,!1,!1))};p.get=function(a){a=this.W(a,!1,!1);var b=K.prototype.get.call(this,a);if(b!==void 0){var c=this.G;return c?(c=this.fa(b,!1,!0,c,this.pa,this.L),c!==b&&K.prototype.set.call(this,a,c),c):b}};L.prototype[Symbol.iterator]=function(){return this.entries()};
L.prototype.toJSON=void 0;function Hc(a,b,c,d,e,k){a=Ac(a,d,c,k);e&&(a=Lc(a));return a}function Kc(a){return[a,this.get(a)]}var Mc;function Nc(){return Mc||(Mc=new L(Hb([]),void 0,void 0,void 0,Dc))};function Oc(a,b,c,d){var e=d!==void 0;d=!!d;var k=[],f=a.length,g=4294967295,h=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,g=f):n=void 0;if(l&&!(b&128)&&!e){h=!0;var q;g=((q=Pc)!=null?q:Cc)(g-m,m,a,n,void 0)+m}}b=void 0;for(e=0;e<f;e++)if(q=a[e],q!=null&&(q=c(q,d))!=null)if(l&&e>=g){var t=e-m,y=void 0;((y=b)!=null?y:b={})[t]=q}else k[e]=q;if(n)for(var B in n)a=n[B],a!=null&&(a=c(a,d))!=null&&(f=+B,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<g?k[e]=a:(f=void 0,((f=b)!=null?f:b={})[B]=a));b&&(h?k.push(b):k[g]=b);return k}function Qc(a){a[0]=Rc(a[0]);a[1]=Rc(a[1]);return a}function Rc(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Zb(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Oc(a,b,Rc)}if(a!=null&&a[Bb]===Jb)return Sc(a);if(a instanceof L)return a=a.size!==0?Jc(a,Qc):void 0,a;return}return a}var Pc;
function Sc(a){a=a.j;return Oc(a,a[C]|0,Rc)};function M(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;if(db&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Tc();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var k=c.length;if(k){var f=k-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var h in g)k=
+h,k<f&&(c[k+b]=g[h],delete g[h]);e=e&-16760833|(f&1023)<<14;break a}}if(b){h=Math.max(b,k-(e&128?0:-1));if(h>1024)throw Error("spvt");e=e&-16760833|(h&1023)<<14}}}E(a,e|64|d);return a}function Tc(){if(db)throw Error("carr");if(Ab!=null){var a;var b=(a=tb)!=null?a:tb={};a=b[Ab]||0;a>=5||(b[Ab]=a+1,b=Error(),ab(b,"incident"),bb(b))}};function Uc(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;return a.length===0&&c&1?void 0:Vc(a,c,b)}if(a!=null&&a[Bb]===Jb)return Wc(a);if(a instanceof L){b=a.L;if(b&2)return a;if(a.size){c=Hb(Jc(a));if(a.G)for(a=0;a<c.length;a++){var d=c[a],e=d[1];e==null||typeof e!=="object"?e=void 0:e!=null&&e[Bb]===Jb?e=Wc(e):Array.isArray(e)?e=Vc(e,e[C]|0,!!(b&32)):e=void 0;d[1]=e}return c}}}
function Vc(a,b,c){if(b&2)return a;!c||4096&b||16&b?a=Xc(a,b,!1,c&&!(b&16)):(Gb(a,34),b&4&&Object.freeze(a));return a}function Yc(a,b,c){a=new a.constructor(b);c&&(a.g=Kb);a.h=Kb;return a}function Wc(a){var b=a.j,c=b[C]|0;return F(a,c)?a:Zc(a,b,c)?Yc(a,b):Xc(b,c)}function $c(a){var b=a.j,c=b[C]|0;return Zc(a,b,c)?Yc(a,b,!0):new a.constructor(Xc(b,c,!1))}function Xc(a,b,c,d){d!=null||(d=!!(34&b));a=Oc(a,b,Uc,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Lc(a){var b=a.j,c=b[C]|0;return F(a,c)?Zc(a,b,c)?Yc(a,b,!0):new a.constructor(Xc(b,c,!1)):a}function ad(a){if(a.g!==Kb)return!1;var b=a.j;b=Xc(b,b[C]|0);Gb(b,2048);a.j=b;a.g=void 0;a.h=void 0;return!0}function bd(a){if(!ad(a)&&F(a,a.j[C]|0))throw Error();}function cd(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Zc(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Kb,!0):!1};function N(a,b){a=dd(a.j,b);if(a!==null)return a}function dd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),k=a.length-1;if(!(k<1+(c?0:-1))){if(e>=k){var f=a[k];if(f!=null&&typeof f==="object"&&f.constructor===Object){c=f[b];var g=!0}else if(e===k)c=f;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return g?f[b]=d:a[e]=d,d}return c}}function ed(a,b,c){bd(a);var d=a.j;O(d,d[C]|0,b,c);return a}
function O(a,b,c,d){var e=c+-1,k=a.length-1;if(k>=0&&e>=k){var f=a[k];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=d,b}if(e<=k)return a[e]=d,b;if(d!==void 0){var g;k=((g=b)!=null?g:b=a[C]|0)>>14&1023||536870912;c>=k?d!=null&&(e={},a[k+-1]=(e[c]=d,e)):a[e]=d}return b}function fd(a,b,c){a=a.j;return gd(a,a[C]|0,b,c)!==void 0}
function hd(a,b,c,d,e){var k=a.j,f=k[C]|0;d=F(a,f)?1:d;e=!!e||d===3;d===2&&ad(a)&&(k=a.j,f=k[C]|0);a=id(k,b);var g=a===Eb?7:a[C]|0,h=jd(g,f);var l=4&h?!1:!0;if(l){4&h&&(a=fc(a),g=0,h=kd(h,f),f=O(k,f,b,a));for(var m=0,n=0;m<a.length;m++){var q=c(a[m]);q!=null&&(a[n++]=q)}n<m&&(a.length=n);c=(h|4)&-513;h=c&=-1025;h&=-4097}h!==g&&(E(a,h),2&h&&Object.freeze(a));return a=ld(a,h,k,f,b,d,l,e)}
function ld(a,b,c,d,e,k,f,g){var h=b;k===1||(k!==4?0:2&b||!(16&b)&&32&d)?md(b)||(b|=!a.length||f&&!(4096&b)||32&d&&!(4096&b||16&b)?2:256,b!==h&&E(a,b),Object.freeze(a)):(k===2&&md(b)&&(a=fc(a),h=0,b=kd(b,d),d=O(c,d,e,a)),md(b)||(g||(b|=16),b!==h&&E(a,b)));2&b||!(4096&b||16&b)||cd(c,d);return a}function id(a,b){a=dd(a,b);return Array.isArray(a)?a:Eb}function jd(a,b){2&b&&(a|=2);return a|1}function md(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function P(a,b,c,d,e){var k=a.j,f=k[C]|0;var g=F(a,f);a:{!g&&ad(a)&&(k=a.j,f=k[C]|0);var h=dd(k,b);a=!1;if(h==null){if(g){b=Nc();break a}h=[]}else if(h.constructor===L)if(h.L&2&&!g)h=Jc(h);else{b=h;break a}else Array.isArray(h)?a=!!((h[C]|0)&2):h=[];if(g){if(!h.length){b=Nc();break a}a||(a=!0,Hb(h))}else if(a){a=!1;Ib(h);h=fc(h);for(var l=0;l<h.length;l++){var m=h[l]=fc(h[l]);Array.isArray(m[1])&&(m[1]=Hb(m[1]))}h=Ib(h)}!a&&f&32&&Gb(h,32);d=new L(h,c,d,e);f=O(k,f,b,d);a||cd(k,f);b=d}!g&&c&&(b.pa=
!0);return b}function gd(a,b,c,d){var e=!1;d=dd(a,d,void 0,function(k){var f=Ac(k,c,!1,b);e=f!==k&&f!=null;return f});if(d!=null)return e&&!F(d)&&cd(a,b),d}function Q(a,b,c){var d=a.j,e=d[C]|0;b=gd(d,e,b,c);if(b==null)return b;e=d[C]|0;if(!F(a,e)){var k=Lc(b);k!==b&&(ad(a)&&(d=a.j,e=d[C]|0),b=k,e=O(d,e,c,b),cd(d,e))}return b}function kd(a,b){return a=(2&b?a|2:a&-3)&-273}
function R(a,b){var c=c===void 0?!1:c;a=N(a,b);a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}function nd(a,b){var c=c===void 0?0:c;var d;return(d=qc(N(a,b)))!=null?d:c}function od(a){var b=b===void 0?0:b;a=rc(N(a,28));return a!=null?a:b}function S(a,b){var c=c===void 0?"":c;var d;return(d=I(N(a,b)))!=null?d:c}function pd(a,b,c){c=c===void 0?0:c;var d;return(d=oc(N(a,b)))!=null?d:c}
function qd(a,b,c){if(c!=null&&typeof c!=="boolean")throw a=typeof c,Error("Expected boolean but got "+(a!="object"?a:c?Array.isArray(c)?"array":a:"null")+": "+c);return ed(a,b,c)}function T(a,b,c){ed(a,b,c==null?c:pc(c))}function U(a,b,c){if(c!=null&&typeof c!=="string")throw Error();return ed(a,b,c)}function rd(a,b,c){ed(a,b,c==null?c:nc(c))};function V(a,b,c){this.j=M(a,b,c,2048)}V.prototype.toJSON=function(){return Sc(this)};function sd(a){return JSON.stringify(Sc(a))}V.prototype[Bb]=Jb;V.prototype.toString=function(){return this.j.toString()};function td(a){this.j=M(a,void 0,void 0,2048)}u(td,V);function ud(a){this.j=M(a,void 0,void 0,2048)}u(ud,V);function vd(a){this.j=M(a,void 0,void 0,2048)}u(vd,V);function wd(a){this.j=M(a,void 0,void 0,2048)}u(wd,V);function xd(a){this.j=M(a,void 0,void 0,2048)}u(xd,V);function yd(a){this.j=M(a,void 0,void 0,2048)}u(yd,V);yd.prototype.M=function(){return S(this,3)};yd.prototype.ea=function(a){qd(this,5,a)};function W(a){this.j=M(a,void 0,void 0,2048)}u(W,V);W.prototype.M=function(){return S(this,1)};W.prototype.ea=function(a){qd(this,2,a)};function zd(a){this.j=M(a,void 0,void 0,2048)}u(zd,V);function Ad(a){this.j=M(a,void 0,void 0,2048)}u(Ad,V);function Bd(a){this.j=M(a,void 0,void 0,2048)}u(Bd,V);
function Cd(a){var b=a.j,c=b;b=b[C]|0;var d=void 0===Mb?2:4,e=F(a,b),k=e?1:d;d=k===3;var f=!e;(k===2||f)&&ad(a)&&(c=a.j,b=c[C]|0);a=id(c,7);var g=a===Eb?7:a[C]|0,h=jd(g,b);if(e=!(4&h)){var l=a,m=b,n=!!(2&h);n&&(m|=2);for(var q=!n,t=!0,y=0,B=0;y<l.length;y++){var D=Ac(l[y],yd,!1,m);if(D instanceof yd){if(!n){var ra=F(D);q&&(q=!ra);t&&(t=ra)}l[B++]=D}}B<y&&(l.length=B);h|=4;h=t?h&-4097:h|4096;h=q?h|8:h&-9}h!==g&&(E(a,h),2&h&&Object.freeze(a));if(f&&!(8&h||!a.length&&(k===1||(k!==4?0:2&h||!(16&h)&&32&
b)))){md(h)&&(a=fc(a),h=kd(h,b),b=O(c,b,7,a));f=a;g=h;for(l=0;l<f.length;l++)h=f[l],m=Lc(h),h!==m&&(f[l]=m);g|=8;h=g=f.length?g|4096:g&-4097;E(a,h)}return a=ld(a,h,c,b,7,k,e,d)};function Dd(a){this.j=M(a,void 0,void 0,2048)}u(Dd,V);function Ed(a){this.j=M(a,void 0,void 0,2048)}u(Ed,V);function Fd(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Gd(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function Hd(a){a=a===void 0?document:a;return a.createElement("img")};var Id=[];function Jd(){var a=Id;Id=[];a=v(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;try{b()}catch(c){}}}function Kd(a){Id.push(a);Id.length===1&&(window.Promise?Promise.resolve().then(Jd):(a=window.setImmediate,Rb(a)?a(Jd):setTimeout(Jd,0)))};function Ld(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};var Md={capture:!0},Nd={passive:!0},Od=Gd(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});z.addEventListener("test",null,b)}catch(c){}return a});function Pd(a){return a?a.passive&&Od()?a:a.capture||!1:!1}function Qd(a,b,c,d){typeof a.addEventListener==="function"&&a.addEventListener(b,c,Pd(d))}function Xd(a){var b=X;b.readyState==="complete"||b.readyState==="interactive"?Kd(a):b.addEventListener("DOMContentLoaded",a)}
function Yd(a){var b=window;b.document.readyState==="complete"?Kd(a):b.addEventListener("load",a)};function Zd(a,b,c,d){$d(a,b,c===void 0?null:c,d===void 0?!1:d)}
function $d(a,b,c,d){var e=!1;e=e===void 0?!1:e;a.google_image_requests||(a.google_image_requests=[]);var k=Hd(a.document);if(c||d){var f=function(g){c&&c(g);if(d){g=a.google_image_requests;var h=Ya(g,k);h>=0&&Array.prototype.splice.call(g,h,1)}typeof k.removeEventListener==="function"&&k.removeEventListener("load",f,Pd());typeof k.removeEventListener==="function"&&k.removeEventListener("error",f,Pd())};Qd(k,"load",f);Qd(k,"error",f)}e&&(k.attributionSrc="");k.src=b;a.google_image_requests.push(k)}
function ae(a){var b=window;var c=c===void 0?!1:c;var d;if(d=b.navigator)d=b.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&typeof b.navigator.sendBeacon==="function"?b.navigator.sendBeacon(a):Zd(b,a,void 0,c)};var be=0;function ce(){var a=de(be,document.currentScript);a&&(a.dataset.initialized="true")}function ee(a){return(a=de(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function de(a,b){return(b=b===void 0?null:b)&&b.getAttribute("data-jc")===String(a)?b:document.querySelector('[data-jc="'+a+'"]')}
function fe(a){var b=b===void 0?.01:b;if(!(Math.random()>b)){var c=de(a,document.currentScript);a="https://"+(c&&c.getAttribute("data-jc-rcd")==="true"?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc="+a+"&version="+ee(a)+"&sample="+b;ae(a)}};function ge(a,b){var c=c===void 0?{}:c;this.error=a;this.meta=c;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror"};function he(a){var b=a.toString();a.name&&b.indexOf(a.name)==-1&&(b+=": "+a.name);a.message&&b.indexOf(a.message)==-1&&(b+=": "+a.message);if(a.stack)a:{a=a.stack;var c=b;try{a.indexOf(c)==-1&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n");break a}catch(e){b=c;break a}b=void 0}return b};var ie=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");function je(a,b){this.g=a;this.h=b}function ke(a,b){this.url=a;this.g=!!b;this.depth=null};var le=null;function me(){var a=a===void 0?z:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function ne(){var a=a===void 0?z:a;return(a=a.performance)&&a.now?a.now():null};function oe(a,b){var c=ne()||me();this.label=a;this.type=b;this.value=c;this.duration=0;this.taskId=this.slotId=void 0;this.uniqueId=Math.random()};var Y=z.performance,pe=!!(Y&&Y.mark&&Y.measure&&Y.clearMarks),qe=Gd(function(){var a;if(a=pe){var b=b===void 0?window:b;if(le===null){le="";try{a="";try{a=b.top.location.hash}catch(d){a=b.location.hash}if(a){var c=a.match(/\bdeid=([\d,]+)/);le=c?c[1]:""}}catch(d){}}b=le;a=!!b.indexOf&&b.indexOf("1337")>=0}return a});
function re(){var a=window;this.h=[];this.i=a||z;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=qe()||(b!=null?b:Math.random()<1)}function se(a){a&&Y&&qe()&&(Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}re.prototype.start=function(a,b){if(!this.g)return null;a=new oe(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";Y&&qe()&&Y.mark(b);return a};
re.prototype.end=function(a){if(this.g&&Ob(a.value)){a.duration=(ne()||me())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";Y&&qe()&&Y.mark(b);!this.g||this.h.length>2048||this.h.push(a)}};function te(){this.i="&";this.h={};this.l=0;this.g=[]}function ue(a,b){var c={};c[a]=b;return[c]}function ve(a,b,c,d,e){var k=[];Fd(a,function(f,g){(f=we(f,b,c,d,e))&&k.push(g+"="+f)});return k.join(b)}
function we(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";Pb(c)&&(c=c.split(""));if(a instanceof Array){if(d||(d=0),d<c.length){for(var k=[],f=0;f<a.length;f++)k.push(we(a[f],b,c,d+1,e));return k.join(c[d])}}else if(typeof a==="object")return e||(e=0),e<2?encodeURIComponent(ve(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function xe(a,b,c){b="https://"+b+c;var d=ye(a)-c.length;if(d<0)return"";a.g.sort(function(m,n){return m-n});c=null;for(var e="",k=0;k<a.g.length;k++)for(var f=a.g[k],g=a.h[f],h=0;h<g.length;h++){if(!d){c=c==null?f:c;break}var l=ve(g[h],a.i,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;b+=l;e=a.i;break}c=c==null?f:c}}a="";c!=null&&(a=e+"trn="+c);return b+a}function ye(a){var b=1,c;for(c in a.h)c.length>b&&(b=c.length);return 3997-b-a.i.length-1};var ze=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ae(a,b){if(!b)return a;var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}
function Be(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Be(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))}function Ce(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var k=a.charCodeAt(b-1);if(k==38||k==63)if(k=a.charCodeAt(b+e),!k||k==61||k==38||k==35)return b;b+=e+1}return-1}var De=/#|$/,Ee=/[?&]($|#)/;
function Fe(a,b){for(var c=a.search(De),d=0,e,k=[];(e=Ce(a,d,b,c))>=0;)k.push(a.substring(d,e)),d=Math.min(a.indexOf("&",e)+1||c,c);k.push(a.slice(d));return k.join("").replace(Ee,"$1")}function Ge(a,b){a=Fe(a,"label");b=b!=null?"="+encodeURIComponent(String(b)):"";return Ae(a,"label"+b)};function He(){var a=Ie;this.pinger=Je;this.g=a===void 0?null:a;this.h=null;this.i=!1;this.m=this.l}function Ke(a,b){var c=Le;try{if(c.g&&c.g.g){var d=c.g.start(a.toString(),3);var e=b();c.g.end(d)}else e=b()}catch(g){b=!0;try{se(d),b=c.m(a,new ge(g,{message:he(g)}),void 0,void 0)}catch(h){c.l(217,h)}if(b){var k,f;(k=window.console)==null||(f=k.error)==null||f.call(k,g)}else throw g;}return e}
function Me(a,b){return function(){var c=za.apply(0,arguments);return Ke(a,function(){return b.apply(void 0,c)})}}
He.prototype.l=function(a,b,c,d,e){e=e||"jserror";var k=void 0;try{var f=new te;f.g.push(1);f.h[1]=ue("context",a);b.error&&b.meta&&b.id||(b=new ge(b,{message:he(b)}));if(b.msg){var g=b.msg.substring(0,512);f.g.push(2);f.h[2]=ue("msg",g)}var h=b.meta||{};if(this.h)try{this.h(h)}catch(ta){}if(d)try{d(h)}catch(ta){}d=[h];f.g.push(3);f.h[3]=d;var l;if(!(l=D)){g=z;d=[];h=null;do{var m=g;try{var n;if(n=!!m&&m.location.href!=null)b:{try{lb(m.foo);n=!0;break b}catch(ta){}n=!1}var q=n}catch(ta){q=!1}if(q){var t=
m.location.href;h=m.document&&m.document.referrer||null}else t=h,h=null;d.push(new ke(t||""));try{g=m.parent}catch(ta){g=null}}while(g&&m!==g);t=0;for(var y=d.length-1;t<=y;++t)d[t].depth=y-t;m=z;if(m.location&&m.location.ancestorOrigins&&m.location.ancestorOrigins.length===d.length-1)for(y=1;y<d.length;++y){var B=d[y];B.url||(B.url=m.location.ancestorOrigins[y-1]||"",B.g=!0)}l=d}var D=l;var ra=new ke(z.location.href,!1);l=null;var sc=D.length-1;for(m=sc;m>=0;--m){var Z=D[m];!l&&ie.test(Z.url)&&(l=
Z);if(Z.url&&!Z.g){ra=Z;break}}Z=null;var wf=D.length&&D[sc].url;ra.depth!==0&&wf&&(Z=D[sc]);k=new je(ra,Z);if(k.h){var xf=k.h.url||"";f.g.push(4);f.h[4]=ue("top",xf)}var tc={url:k.g.url||""};if(k.g.url){var uc=k.g.url.match(ze),Rd=uc[1],Sd=uc[3],Td=uc[4];D="";Rd&&(D+=Rd+":");Sd&&(D+="//",D+=Sd,Td&&(D+=":"+Td));var Ud=D}else Ud="";tc=[tc,{url:Ud}];f.g.push(5);f.h[5]=tc;Ne(this.pinger,e,f,this.i,c)}catch(ta){try{var Vd,Wd;Ne(this.pinger,e,{context:"ecmserr",rctx:a,msg:he(ta),url:(Wd=(Vd=k)==null?void 0:
Vd.g.url)!=null?Wd:""},this.i,c)}catch(Zf){}}return!0};function Oe(){};function Pe(){this.domain="pagead2.googlesyndication.com";this.path="/pagead/gen_204?id=";this.g=Math.random()}function Qe(){var a=Je,b=window.google_srt;b>=0&&b<=1&&(a.g=b)}function Ne(a,b,c,d,e){if(((d===void 0?0:d)?a.g:Math.random())<(e||.01))try{if(c instanceof te)var k=c;else k=new te,Fd(c,function(g,h){var l=k,m=l.l++;g=ue(h,g);l.g.push(m);l.h[m]=g});var f=xe(k,a.domain,a.path+b+"&");f&&Zd(z,f)}catch(g){}};var Re=[Na,Oa,Qa,Pa,Ma,Sa,Ta,Ra,Ua];function Se(a,b){if(a instanceof Ja)return a;var c=Re;c=c===void 0?Va:c;a:if(c=c===void 0?Va:c,a instanceof Ja)c=a;else{for(var d=0;d<c.length;++d){var e=c[d];if(e instanceof La&&e.ra(a)){c=new Ja(a);break a}}c=void 0}c=c||Ka;c===Ka&&b(a);return c}
function Te(a){return function(b){b={id:"unsafeurl",ctx:a,url:b};var c=[];for(d in b)Be(d,b[d],c);var d=Ae("https://pagead2.googlesyndication.com/pagead/gen_204",c.join("&"));navigator.sendBeacon&&navigator.sendBeacon(d,"")}};var Je,Le,Ie=new re;function Ue(){if(!window.google_measure_js_timing){var a=Ie;a.g=!1;a.h!==a.i.google_js_reporting_queue&&(qe()&&Za(a.h,se),a.h.length=0)}}(function(a){Je=a!=null?a:new Pe;typeof window.google_srt!=="number"&&(window.google_srt=Math.random());Qe();Le=new He;Le.h=function(b){var c=be;c!==0&&(b.jc=String(c),b.shv=ee(c))};Le.i=!0;window.document.readyState==="complete"?Ue():Ie.g&&Qd(window,"load",function(){Ue()})})();function Ve(a,b){return Me(a,b)}
function We(a,b){var c="ca";Oe.ca&&Oe.hasOwnProperty(c)||(c=new Oe,Oe.ca=c);c=[];!b.eid&&c.length&&(b.eid=c.toString());Ne(Je,a,b,!0)};function Xe(){var a=a===void 0?z:a;return a.oneAfmaInstance};var X=document,Ye=window;function Ze(a){var b=X;try{return b.querySelectorAll("*["+a+"]")}catch(c){return[]}};Ld({Da:0,Ca:1,za:2,ua:3,Aa:4,va:5,Ba:6,xa:7,ya:8,ta:9,wa:10,Ea:11}).map(function(a){return Number(a)});Ld({Ga:0,Ha:1,Fa:2}).map(function(a){return Number(a)});function $e(a){this.j=M(a,void 0,void 0,2048)}u($e,V);function af(a){var b=new $e;bd(b);b=hd(b,1,oc,2,!0);if(Array.isArray(a))for(var c=a.length,d=0;d<c;d++)b.push(nc(a[d]));else for(a=v(a),c=a.next();!c.done;c=a.next())b.push(nc(c.value))};[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});af([1,8,9,10,11,12,2,3,4,5,15,16,19,20,21,23,25]);af([1,6,7,9,10,11,12,2,22,3,4,5,13,14,18,19,20,21,23,24]);af([1,6,7,9,10,11,12,22,2,3,4,5,13,14,17,18,19,20,21,23,24]);new $e;function bf(a){this.j=M(a,void 0,void 0,2048)}u(bf,V);function cf(a,b){b=S(a,2)||b;if(!b)return"";if(R(a,13))return b;var c=/[?&]adurl=([^&]+)/.exec(b);if(!c)return b;var d=[b.slice(0,c.index+1)];P(a,4,void 0,J,J).forEach(function(e,k){d.push(encodeURIComponent(k)+"="+encodeURIComponent(e)+"&")});d.push(b.slice(c.index+1));return R(a,27)?(b=d.join(""),(a=P(a,4,void 0,J,J).get("label"))&&(b=Ge(b,a)),b):d.join("")}
function df(a,b,c){b=b===void 0?[]:b;c=c===void 0?!1:c;b=b.length>0?b:Ze("data-asoch-targets");a=P(a,1,Bd,J);for(var d=[],e=0;e<b.length;++e){for(var k=b[e].getAttribute("data-asoch-targets"),f=k.split(","),g=!0,h=v(f),l=h.next();!l.done;l=h.next())if(!a.has(l.value)){g=!1;break}if(g){g=a.get(f[0]);for(k=1;k<f.length;++k){h=a.get(f[k]);g=$c(g);g=Sc(g);l=Sc(h);for(var m=Math.max(g.length,l.length),n=0;n<m;++n)g[n]==null&&(g[n]=l[n]);l=g=new Bd(g);m=(od(g)||0)|(od(h)||0);h=l;if(m==null)l=m;else{l=m;
if(typeof l!=="number")throw ub("uint32");if(!jc(l))throw ub("uint32");l>>>=0}ed(h,28,l)}f=P(g,4,void 0,J,J);oc(N(g,5))!=null&&f.set("nb",pd(g,5).toString());od(g)&&c&&f.set("als",od(g).toString());d.push({element:b[e],data:g})}else We("gdn-asoch",{type:1,data:k})}return d}
function ef(a,b,c,d){c=cf(b,c);if(c.length!==0){if(d===609&&fd(b,td,24)){var e=Q(b,td,24);a.setAttribute("attributionDestination",S(e,2));a.setAttribute("attributionSourceNonce",S(e,1))}(e=(e=de(35))&&e.dataset.expanded?e.dataset.expanded:null)&&d===557&&(c=ff(c,"expanded",e));Xa(a,Se(c,Te(d)));a.target||(a.target=I(N(b,11))!=null?S(b,11):"_top")}}
function gf(a){var b=b===void 0?"":b;var c=c===void 0?!1:c;a=v(a);for(var d=a.next();!d.done;d=a.next()){var e=d.value;d=e.data;var k=b.length===0?!1:e.element.matches(b);e.element.tagName!="A"||R(d,1)||k||(e=e.element,ef(e,d,e.href,c?1087:609))}}function ff(a,b,c){b=encodeURIComponent(b);var d=encodeURIComponent(c);c=new RegExp("[?&]"+b+"=([^&]+)");var e=c.exec(a);b=b+"="+d;return e?a.replace(c,e[0].charAt(0)+b):a.replace("?","?"+b+"&")}
function hf(a){var b=Xe();if(b){var c=v(a);for(a=c.next();!a.done;a=c.next()){var d=a.value.data;if(d&&fd(d,zd,8)&&(a=Q(d,zd,8),a=S(a,4))){c=b.fetchAppStoreOverlay;d=Q(d,zd,8);d=S(d,6);c.call(b,a,void 0,d);break}}}}
function jf(a,b){function c(g,h){if(h){g=v(e);for(var l=g.next();!l.done;l=g.next())l=l.value,h[l.M()]&&l.ea(!0)}}b=b===void 0?500:b;var d=[],e=[];a=v(a);for(var k=a.next();!k.done;k=a.next())(k=k.value.data)&&fd(k,W,12)&&(e.push(Q(k,W,12)),d.push(Q(k,W,12).M()));a=Xe();d=v(d);for(k=d.next();!k.done;k=d.next()){k=k.value;var f=void 0;(f=a)==null||f.canOpenAndroidApp(k,c,function(){},b)}}
function kf(a,b,c,d){function e(B){return d.openStoreOverlay(B,l,m,S(k,6))}if(!b||!fd(b,zd,8))return!1;var k=Q(b,zd,8),f=S(k,2);P(b,10,void 0,J,J).forEach(function(B,D){f=ff(f,D,B)});lf(b)&&R(b,15)&&!/[?&]label=/.test(c)&&(c=mf(c,"label","deep_link_fallback"));if(a==null?0:R(a,1))S(b,9)?We("skspvc",{url:1}):We("skspvc",{url:0});var g=a==null?void 0:R(a,7),h=S(b,9),l=void 0,m=void 0,n=-1;if(g&&h){var q=Ge(h,"skspvc_triggered"),t=Ge(h,"skspvc_registered"),y=Ge(h,"skspvc_dismissed");l=function(){ae(q);
n=setTimeout(function(){ae(t)},3E3)};m=function(){ae(y);clearTimeout(n)}}return d.redirectForStoreU2({clickUrl:c,trackingUrl:S(k,3),finalUrl:f,pingFunc:R(b,13)?d.httpTrack:d.click,openFunc:(a==null?0:R(a,1))?e:d.openIntentOrNativeApp,isExternalClickUrl:R(b,13)})}
function nf(a,b,c,d,e,k){k=k===void 0?!1:k;d&&d.startsWith("intent:")?e.openIntentOrNativeApp(d):k?e.openWebApp(d,void 0,void 0,!0,!0):a&&!c?e.openChromeCustomTab(d,{cct_init_h:"200",cct_bp:"2"}):b?c?e.openBrowser(d):e.openChromeCustomTab(d):e.openSystemBrowser(d,{useFirstPackage:!0,useRunningProcess:!0})}
function of(a,b){b=b===void 0?null:b;if(b===null){b=new Fa({url:a,sa:null});if(b.g.dsh==="1"||b.g.aspm!=="1"){var c=Ga(b,0);a=c?navigator.sendBeacon?navigator.sendBeacon(c.T,"")?c.V:Ia(b,2):Ia(b,0):a}else if(b=Ga(b,1))fetch(b.T,{keepalive:!0,mode:"no-cors",credentials:"include"}),a=b.V;return a}c=Ga(new Fa({url:a}),0);if(!c)return a;b(c.T);return c.V}function pf(a,b){(b===void 0||b)&&Ye.fetch?Ye.fetch(a,{method:"GET",keepalive:!0,mode:"no-cors"}).then(function(c){c.ok||Zd(Ye,a)}):Zd(Ye,a)}
function mf(a,b,c){b=encodeURIComponent(String(b));c=encodeURIComponent(String(c));return a.replace("?","?"+b+"="+c+"&")}function lf(a){a=v(Cd(a));for(var b=a.next();!b.done;b=a.next())if(b=b.value,pd(b,1)===3&&S(b,2))return!0;return!1};function qf(a,b){return a&&(a=a.match(b+"=([^&]+)"))&&a.length==2?a[1]:""};function rf(a){this.j=M(a,void 0,void 0,2048)}u(rf,V);function sf(a){this.j=M(a,void 0,void 0,2048)}u(sf,V);function tf(a,b){return U(a,2,b)}function uf(a,b){return U(a,3,b)}function vf(a,b){return U(a,4,b)}function yf(a,b){return U(a,5,b)}function zf(a,b){return U(a,9,b)}
function Af(a,b){bd(a);var c=a.j,d=c[C]|0;if(b==null)O(c,d,10);else{for(var e=b===Eb?7:b[C]|0,k=e,f=md(e),g=f||Object.isFrozen(b),h=!0,l=!0,m=0;m<b.length;m++){var n=b[m];f||(n=F(n),h&&(h=!n),l&&(l=n))}f||(e=h?13:5,e=l?e&-4097:e|4096);g&&e===k||(b=fc(b),k=0,e=kd(e,d));e!==k&&E(b,e);d=O(c,d,10,b);2&e||!(4096&e||16&e)||cd(c,d)}return a}function Bf(a,b){return qd(a,11,b)}function Cf(a,b){return U(a,1,b)}function Df(a,b){return qd(a,7,b)};var Ef="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function Ff(a){var b;return(b=a.google_tag_data)!=null?b:a.google_tag_data={}}function Gf(a){var b,c;return typeof((b=a.navigator)==null?void 0:(c=b.userAgentData)==null?void 0:c.getHighEntropyValues)==="function"}
function Hf(){var a=window;if(!Gf(a))return null;var b=Ff(a);if(b.uach_promise)return b.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(Ef).then(function(c){b.uach!=null||(b.uach=c);return c});return b.uach_promise=a}
function If(a){var b;return Bf(Af(yf(tf(Cf(vf(Df(zf(uf(new sf,a.architecture||""),a.bitness||""),a.mobile||!1),a.model||""),a.platform||""),a.platformVersion||""),a.uaFullVersion||""),((b=a.fullVersionList)==null?void 0:b.map(function(c){var d=new rf;d=U(d,1,c.brand);return U(d,2,c.version)}))||[]),a.wow64||!1)}function Jf(){var a,b;return(b=(a=Hf())==null?void 0:a.then(function(c){return If(c)}))!=null?b:null};function Kf(a){var b=this;this.v=pb||nb||qb||ob;var c=Ze("data-asoch-meta");if(c.length!==1)We("gdn-asoch",{type:2,data:c.length});else{this.O=70;this.h=new Dd(JSON.parse(c[0].getAttribute("data-asoch-meta"))||[]);this.J=a["extra-meta"]?new Dd(JSON.parse(a["extra-meta"])):null;this.N=a["is-fsn"]==="true";this.ka=a["is-tap-disabled-for-fsn"]==="true";this.m=a["ios-store-overlay-config"]?new xd(JSON.parse(a["ios-store-overlay-config"])):null;this.ma=a["use-cct-over-browser"]==="true";this.ga=a["enable-ios-webview"]===
"true";this.ha=a["enable-lock-screen-ad-custom-webview"]==="true";this.na=a["use-half-page-cct-over-browser"]==="true";this.Z=a["correct-redirect-url-for-och-15-click"]==="true";this.la=a["spitzer-use-click-url-for-fallback"]==="true";this.D=a["default-msg-in-och"]==="true";this.ia=a["enable-paw"]==="true";this.H=a["allow-redirection-muted-in-och"]==="true";this.I=Number(a["custom-async-tracking-throttle-interval"])||-1;this.Y=a["populate-ad-lifecycle-state"]==="true";this.o="";c=Jf();c!=null&&c.then(function(e){var k=
sd(e);e=[];for(var f=0,g=0;g<k.length;g++){var h=k.charCodeAt(g);h>255&&(e[f++]=h&255,h>>=8);e[f++]=h}k=3;k===void 0&&(k=0);if(!sb)for(sb={},f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),g=["+/=","+/","-_=","-_.","-_"],h=0;h<5;h++){var l=f.concat(g[h].split(""));rb[h]=l;for(var m=0;m<l.length;m++){var n=l[m];sb[n]===void 0&&(sb[n]=m)}}k=rb[k];f=Array(Math.floor(e.length/3));g=k[64]||"";for(h=l=0;l<e.length-2;l+=3){var q=e[l],t=e[l+1];n=e[l+2];m=k[q>>2];q=k[(q&3)<<4|
t>>4];t=k[(t&15)<<2|n>>6];n=k[n&63];f[h++]=m+q+t+n}m=0;n=g;switch(e.length-l){case 2:m=e[l+1],n=k[(m&15)<<2]||g;case 1:e=e[l],f[h]=k[e>>2]+k[(e&3)<<4|m>>4]+n+g}b.o=f.join("")});this.g=df(this.h,[],this.Y);this.D&&(this.l=null,P(this.h,1,Bd,J).forEach(function(e){b.l!=null||I(N(e,2))==null||I(N(e,9))==null||R(e,13)||(b.l=e)}));this.oa=Number(a["deeplink-and-android-app-validation-timeout"])||500;this.P=-Infinity;this.u=this.K=0;this.i=S(this.h,5)||"";this.X=R(this.h,11);this.J&&(this.X=R(this.J,11));
this.A=this.aa=this.R=this.S=this.C=null;R(this.h,3)||(gf(this.g),qd(this.h,3,!0));Lf(this.g);a=Xe();!this.v&&a&&jf(this.g,this.oa);var d;if(a&&((d=this.m)==null?0:R(d,2)))switch(d=function(){var e=nd(b.m,4);e>0?z.setTimeout(function(){hf(b.g)},e):hf(b.g)},pd(this.m,3)){case 1:a.runOnOnShowEvent(d);break;case 2:Yd(d);break;default:hf(this.g)}Qd(X,"click",Ve(557,function(e){Mf(b,e)}),Md);Qd(X,"auxclick",Ve(557,function(e){e.button===1&&Mf(b,e)}),Md);this.i&&typeof window.ss==="function"&&Qd(X.body,
"mouseover",Ve(626,function(){window.ss(b.i,0)}),Nd);typeof window.ivti==="function"&&window.ivti(X.body);d=window;d.googqscp&&typeof d.googqscp.registerCallback==="function"&&d.googqscp.registerCallback(function(e,k,f,g,h){b.C=e;b.A=k;b.S=f;b.R=g;b.aa=h});ce()}}
function Mf(a,b){if(!b.defaultPrevented||a.C===b){for(var c,d,e=b.target;(!c||!d)&&e;){d||e.tagName!="A"||(d=e);var k=e.hasAttribute("data-asoch-targets"),f=e.hasAttribute("data-asoch-fixed-value");if(!c)if(f)c=new Bd(JSON.parse(e.getAttribute("data-asoch-fixed-value"))||[]);else if(e.tagName=="A"||k)if(k=k&&e.getAttribute("data-asoch-is-dynamic")==="true"?df(a.h,[e],a.Y):a.g,k=Nf(k,e))c=k.data;e=e.parentElement}e=c&&!R(c,1);if(a.D&&a.l&&b.defaultPrevented)Of(a,b,d,e?c:a.l);else{if(e){if(!a.D&&b.defaultPrevented){Of(a,
b,d,c);return}k=v(hd(c,6,I,void 0===Mb?2:4));for(f=k.next();!f.done;f=k.next())pf(f.value)}a.H&&e&&R(c,21)&&(b.preventDefault?b.preventDefault():b.returnValue=!1);if(d&&e){c=e?c:null;(e=Nf(a.g,d))?e=e.data:(e=new Bd,U(e,2,d.href),U(e,11,d.target||"_top"),a.g.push({element:d,data:e}));ef(d,c||e,S(e,2),557);Pf(a,b,d,c);e=v(hd(a.h,17,I,void 0===Mb?2:4));for(f=e.next();!f.done;f=e.next()){k=void 0;var g=f.value,h=X.body;k=k===void 0?{}:k;typeof window.CustomEvent==="function"?f=new CustomEvent(g,k):(f=
document.createEvent("CustomEvent"),f.initCustomEvent(g,!!k.bubbles,!!k.cancelable,k.detail));h.dispatchEvent(f)}var l;if(c==null?0:(l=Q(c,Ad,26))==null?0:I(N(l,1))!=null){l=new ud;oc(N(c,5))!=null?(e=pd(c,5),rd(l,1,e)):(e=qf(d.href,"nb"),e!=""&&rd(l,1,+e));e=qf(d.href,"nx");e!=""&&T(l,2,+e);e=qf(d.href,"ny");e!=""&&T(l,3,+e);e=qf(d.href,"bg");e!=""&&U(l,4,e);e=qf(d.href,"nm");e!=""&&T(l,5,+e);e=qf(d.href,"mb");e!=""&&T(l,6,+e);e=Fe(d.href,"bg");Xa(d,Se(e,Te(1211)));e=Q(c,Ad,26);f=S(e,1);e=Q(c,Ad,
26);e=S(e,2);k=qc(N(c,20))!=null?nd(c,20):null;h=sd(l);l=a.o;g=z;g=g===void 0?window:g;var m=new Ed;f=U(m,1,f);f=U(f,4,h);f=U(f,10,Date.now().toString());k!==null&&T(f,2,k);l!==null&&U(f,3,l);rd(f,9,7);var n;g==null||(n=g.fence)==null||n.setReportEventDataForAutomaticBeacons({eventType:"reserved.top_navigation_start",eventData:JSON.stringify(f),destination:["buyer"],once:!0});var q;g==null||(q=g.fence)==null||q.reportEvent({eventType:"click",eventData:e,destination:["component-seller"]})}R(a.h,16)||
a.N?Qf(a,b,d,c):(n="",(q=Xe())&&(n=q.appendClickSignals(d.href)),Rf(a,b,d,c,n))}}}}
function Of(a,b,c,d){if(a.C===b&&a.A){var e=new wd(a.A),k=S(d,9),f="";switch(pd(e,4,1)){case 2:if(nd(e,2))f="blocked_fast_click";else if(S(e,1)||S(e,7))f="blocked_border_click";break;case 3:var g=g===void 0?X:g;f=g.getElementById?g.getElementById("common_15click_anchor"):null;g=window;if(typeof g.copfcChm==="function"&&f){var h=$c(d);rd(h,5,12);P(h,4,void 0,J,J).set("nb",(12).toString());var l=Nf(a.g,f);l?l.data=h:a.g.push({element:f,data:h});!a.Z&&c&&(Pf(a,b,c,h),U(h,2,c.href));g.copfcChm(b,cf(h,
f.href),null,fd(e,vd,10)?sd(Q(e,vd,10)):null);a.Z&&Pf(a,b,f,h)}f="onepointfiveclick_first_click"}if(k&&f){c=k+"&label="+f;if(f==="onepointfiveclick_first_click"||f==="blocked_border_click"){g=a.S;f=a.R;k=a.aa;e=new bf;d=pd(d,5);h=b.clientX;ed(e,1,h==null?h:vc(h));h=b.clientY;ed(e,2,h==null?h:vc(h));T(e,3,d);d=g?g.changedTouches:[];f=f?f.changedTouches:[];d&&d.length>0&&(T(e,4,d[0].clientX),T(e,5,d[0].clientY));f&&f.length>0&&(T(e,6,f[0].clientX),T(e,7,f[0].clientY));(b.isTrusted===!1||navigator.userActivation&&
navigator.userActivation.hasBeenActive===!1||navigator.userActivation&&navigator.userActivation.isActive===!1)&&qd(e,8,!0);if(k!=null)for(b=v(Object.entries(k)),d=b.next();!d.done;d=b.next())k=v(d.value),d=k.next().value,k=k.next().value,d=Number(d),k=Date.now()-Number(k),P(e,9,void 0,Bc,Bc).set(d,k);c+="&cpspb="+sd(e)}pf(c,!1)}fe(a.O)}}
function Qf(a,b,c,d){var e,k,f;ya(new xa(new sa(function(g){switch(g.g){case 1:e="";k=Xe();if(!k){g.F(2);break}b.preventDefault();return g.v(k.appendClickSignalsAsync(c.href),3);case 3:e=g.o||"";if(!a.N){g.F(2);break}return a.ka?g.return():g.v(k.getNativeClickMeta(),5);case 5:if(f=g.o){if(f.customClickGestureEligible)return g.return();e=mf(e,"nas",f.encodedNas)}case 2:Rf(a,b,c,d,e),g.D()}})))}
function Rf(a,b,c,d,e){a.K++;a.u<0&&(a.u=Date.now());var k=R(a.h,2),f=a.I>0?a.I:300;f=k&&Date.now()-a.P>f;var g=Xe();if(g)if(b.preventDefault?b.preventDefault():b.returnValue=!1,c=R(d,13)?e:g.logScionEventAndAddParam(e),a.ga)g.openWebApp(c);else{if(!a.v&&d&&fd(d,W,12)){b=Q(d,W,12).M();e="";if(Cd(d).length>0)for(var h=v(Cd(d)),l=h.next();!l.done;l=h.next())l=l.value,e+=S(l,2)+" "+l.M()+" ";e=Q(d,W,12);R(e,2)?(g.click(c),g.openAndroidApp(b),b=!0):b=!1}else b=!1;if(!b&&!kf(a.m,d,c,g))a:{b=a.na;e=a.ma;
h=a.v;l=a.H;var m=a.la,n=a.ha;l=l===void 0?!1:l;m=m===void 0?!1:m;n=n===void 0?!1:n;var q=R(d,15);if(!m&&q&&I(N(d,22))!=null)nf(b,e,h,S(d,22),g,n);else{var t=Ga(new Fa({url:c}),0);m=q&&(t&&t.version===3||m);if(k&&f&&!m&&(c=of(c,g.click),l&&(d==null?0:R(d,21))))break a;nf(b,e,h,c,g,n)}}}else d=window,a.ia&&d.pawsig&&typeof d.pawsig.clk==="function"?(We("paw_sigs",{msg:"click",count:a.K.toString(),elapsed:(Date.now()-a.u).toString()}),f&&d.pawsig.clk(c)):f&&(d=of(c.href),d!==c.href&&Xa(c,Se(d,Te(599))));
f&&(a.P=Date.now());fe(a.O)}
function Pf(a,b,c,d){if(!R(d,13)){var e=c.href;var k=/[?&]adurl=([^&]+)/.exec(e);e=k?[e.slice(0,k.index),e.slice(k.index)]:[e,""];for(Xa(c,Se(e[0],Te(557)));!c.id;)if(k="asoch-id-"+(Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36)),!X.getElementById(k)){c.id=k;break}k=c.id;typeof window.xy==="function"&&window.xy(b,c,X.body);typeof window.mb==="function"&&window.mb(c);typeof window.bgz==="function"&&window.bgz(k);typeof window.ja===
"function"&&window.ja(k,d?pd(d,5):0);typeof window.vti==="function"&&window.vti(c);a.i&&typeof window.ss==="function"&&(a.X?window.ss(k,1,a.i):window.ss(a.i,1));if(e.length>0){var f;b=a.o.length>0&&(d==null||(f=Q(d,Ad,26))==null||I(N(f,1))==null)?c.href+"&uach="+encodeURIComponent(a.o)+e[1]:c.href+e[1];Xa(c,Se(b,Te(557)))}}}function Sf(a){Xd(Ve(556,function(){new Kf(a||{})}))}function Nf(a,b){return $a(a,function(c){return c.element===b})}
function Lf(a){a=v(a);for(var b=a.next();!b.done;b=a.next()){var c=b.value;c.element.tagName=="A"&&(b=c.element,c=c.data,I(N(c,2))!=null||U(c,2,b.href))}};var Tf=Ve(555,function(a){return Sf(a)});be=70;var Uf=de(70,document.currentScript);if(Uf==null)throw Error("JSC not found 70");for(var Vf={},Wf=Uf.attributes,Xf=Wf.length-1;Xf>=0;Xf--){var Yf=Wf[Xf].name;Yf.indexOf("data-jcp-")===0&&(Vf[Yf.substring(9)]=Wf[Xf].value)}Tf(Vf);}).call(this);
